name: AWS S3 Upload New Files

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      # 追加: yyyymmを動的に設定する部分（例: タグから取得）
      - name: Extract yyyymm from Git Tag
        run: echo "yyyymm=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Upload New Files to AWS S3
        run: |
          aws s3 sync --exact-timestamps --size-only ./html-pickup_${{ env.yyyymm }} s3://html-pickup/${{ env.yyyymm }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
