name: AWS S3 Upload New Files

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      # 追加: yyyymmを動的に設定する部分（例: 現在の日付から取得）
      - name: Extract yyyymm from Current Date
        run: echo "yyyymm=$(date +'%Y%m')" >> $GITHUB_ENV

      - name: Upload New Files to AWS S3
        run: |
          aws s3 sync --exact-timestamps --size-only ./html-pickup_202308 s3://html-pickup }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
