name: html-pickupALL

on:
  schedule:
    - cron: "0 */24 * * *"  
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "my_value"  # 任意の変数名と値を設定します

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install notebook requests bs4 dropbox pandas
      - name: Run scraper
        run: python topics_scraper_all_Ver.5.1.py

      - name: Get current date
        id: get_date
        run: echo "TODAY=$(date +'%Y%m')" >> $GITHUB_ENV

      - name: Create directory
        run: mkdir html-pickup_${TODAY}

      - name: Save state
        run: echo "name=$MY_VARIABLE" >> $GITHUB_STATE

      - name: Set output
        run: echo "name=$MY_VARIABLE" >> $GITHUB_OUTPUT

      - name: Add and commit
        id: add_commit
        run: |
          git config --global user.name "Automated"
          git config --global user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Latest data"

      - name: Archive files
        run: tar czvf html-pickup_${TODAY}.tar.gz html-pickup_${TODAY}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html_pickup_${TODAY}
          path: html-pickup_${TODAY}.tar.gz
