name: html-pickupALL02

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "my_value"  # 任意の変数名と値を設定します

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install notebook requests bs4 dropbox pandas
      - name: Create directory for artifacts
        run: |
          month=$(date +'%Y%m')
          mkdir -p "html-pickup_${month}"
      - name: Run scraper
        run: python topics_scraper_all_Ver.5.1.py

      # CSVファイルをコミットしてプッシュ
      - name: Commit and push CSV files
        run: |
          month=$(date +'%Y%m')
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add html-pickup_${month}/
          git commit -m "Update csv files"
          git push
