name: html-mediaALL_b

on:
  schedule:
    - cron: "0 4 * * 1,4" # every Monday and Thursday at 4 AM
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install required libraries
        run: pip install notebook requests bs4 dropbox pandas
        
      - name: Create directory for artifacts
        run: |
          month=$(date +'%Y%m')
          week=$(date +'%Y%m_%W')
          mkdir -p "html-mediaALL_b_${month}"

      - name: Run scraper
        run: python media_scraper_group_b_Ver.3.6.py
      
      - name: Set Git Config
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
        working-directory: ${{ github.workspace }}
        
      - name: Commit and push XML files
        run: |
          git add .
          git commit -m "Update csv files"
          git push
        working-directory: ${{ github.workspace }}
