name: html-pickupALL

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install notebook requests bs4 dropbox pandas

      - name: Run scraper and get file names
        id: run_scraper
        run: |
          # スクレイプを実行してファイルを生成
          python topics_scraper_all_Ver.5.1.py

          # スクレイプした結果からファイル名を取得してリストに格納
          scraped_files=$(find . -name "html_*.csv")
          echo "SCRAPED_FILES=$scraped_files" >> $GITHUB_ENV

      - name: Create target folder
        run: |
          # 今日の日付を取得してフォルダ名を作成（フォルダ名は%Y%m形式）
          today=$(date +'%Y%m')
          mkdir -p html-pickup_${today}

      - name: Copy generated files to target folder
        run: |
          # スクレイプしたファイルをターゲットフォルダにコピーします
          for file in $SCRAPED_FILES; do
            if [ -f "$file" ]; then
              cp $file html-pickup_${today}
            else
              echo "File not found: $file"
            fi
          done

      - name: Archive new files
        run: tar czvf html-pickup_${today}.tar.gz html-pickup_${today}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html_pickup_${today}
          path: html-pickup_${today}.tar.gz

