name: html-pickupALL

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install notebook requests bs4 dropbox pandas

      - name: Run scraper
        run: python topics_scraper_all_Ver.5.1.py

      - name: Create directory for artifacts
        run: |
          month=$(date +'%Y%m')
          mkdir -p "html-pickup_${month}"

      - name: Move CSV files to artifact directory
        run: |
          month=$(date +'%Y%m')
          mv html-pickup_202307/*.csv "html-pickup_${month}/"

      - name: Archive new files
        run: |
          month=$(date +'%Y%m')
          tar czvf "html-pickup_${month}.tar.gz" "html-pickup_${month}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html-pickup
          path: "html-pickup_${month}.tar.gz"
