name: html-mediaALL_a

on:
  schedule:
    - cron: "0 2 * * *"　# 毎日02時に実行
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install required libraries
        run: pip install notebook requests bs4 dropbox pandas
      - name: Run scraper
        run: python media_scraper_group_a_Ver.3.6.py

      # CSVファイルをコミットしてプッシュ
      - name: Add and commit
        run: |
          month=$(date +'%Y%m')
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p html_mediaALL_a_${month}/
          git add html_mediaALL_a_${month}/
          git commit -m "Latest data_a - $(date +'%Y-%m-%d %H:%M:%S')"
          set -e  # エラーチェックを追加
          git pull origin main --ff-only  # プル時に競合を避ける
          git push
