name: html-mediaALL

on:
  schedule:
    - cron: "*/10 * * * *" 
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install notebook requests bs4 dropbox pandas
      - name: Run scraper
        run: python media_scraper_group_Ver.3.6.py

      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@v8
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "Latest data"
