name: Run Python media_all every day

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests==2.26.0
          python -m pip install beautifulsoup4==4.9.3
          python -m pip install pandas==1.3.0
          python -m pip install numpy==1.22.0
          python -m pip install matplotlib==3.4.2
          python -m pip install dropbox==11.16.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: |
          python media_all_dropbox.py
